# Generated by Django 3.0.6 on 2020-07-15 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_auto_20200715_0546'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todomodels',
            name='content',
        ),
        migrations.RemoveField(
            model_name='todomodels',
            name='date',
        ),
    ]
