# Generated by Django 3.0.6 on 2020-07-15 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0003_auto_20200715_0554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todomodels',
            name='title',
        ),
        migrations.AddField(
            model_name='todomodels',
            name='content',
            field=models.TextField(default='Enter the tasks', max_length=200),
        ),
    ]
